### PR TITLE
Download of VC is started when clicking "Back home" rather than when entering verification code

### LINKED ISSUE #85: Download of VC is started when clicking "Back home" rather than when entering verification code
**Describe the bug**
Currently the download of VC will start when clicking "Back home" rather than when entering verification code.

**To Reproduce**
1. Enter UIN and verification code
2. When on confirmation screen, do not click "Back home" until several minutes have passed
3. Click "Back home". Note that download has still not been done

**Expected behavior**
Download should be initiated when entering verification code and proceed in the background even if user does not return to "My VC" screen

**Screenshots**

**Desktop (please complete the following information):**

**Identified on:**
0.2.1 beta 4

### PR DESCRIPTION
**Pull request by danicaerediano**
Closes #85

### CODE REVIEW

File: screens/Home/MyVids/AddVidModalMachine.ts [hunk 1]
```diff
@@ -165,6 +166,7 @@ export const AddVidModalMachine = model.createMachine(
         },
       },
       requestSuccessful: {
+        entry: [send('DISMISS')],
```
Comment (pmigueld) [inline screens/Home/MyVids/AddVidModalMachine.ts:169]: You can just remove this state and transition to `done`.

**Comment by danicaerediano** [comment]
don't merge this yet pls

**Review by pmigueld — APPROVED** [review]
